// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALxfconxLk1uEyiuCR8dpNYPCpPeNJps4',
    appId: '1:264463585580:web:b9c44d994613ad9f9edc89',
    messagingSenderId: '264463585580',
    projectId: 'market-linkage-application',
    authDomain: 'market-linkage-application.firebaseapp.com',
    storageBucket: 'market-linkage-application.firebasestorage.app',
    measurementId: 'G-LJF4DRQG2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYO99XAOaoft5ukMx07gfxZXA3FgfeiFY',
    appId: '1:264463585580:android:faa2bb04c4f457079edc89',
    messagingSenderId: '264463585580',
    projectId: 'market-linkage-application',
    storageBucket: 'market-linkage-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdV6W6kw7eAgfFxOEAhec2NWQQqiYqHzQ',
    appId: '1:264463585580:ios:1ec553145de406779edc89',
    messagingSenderId: '264463585580',
    projectId: 'market-linkage-application',
    storageBucket: 'market-linkage-application.firebasestorage.app',
    iosBundleId: 'com.gasper.marketlink.marketLinkageApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdV6W6kw7eAgfFxOEAhec2NWQQqiYqHzQ',
    appId: '1:264463585580:ios:1ec553145de406779edc89',
    messagingSenderId: '264463585580',
    projectId: 'market-linkage-application',
    storageBucket: 'market-linkage-application.firebasestorage.app',
    iosBundleId: 'com.gasper.marketlink.marketLinkageApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALxfconxLk1uEyiuCR8dpNYPCpPeNJps4',
    appId: '1:264463585580:web:691abf4078e9a6e69edc89',
    messagingSenderId: '264463585580',
    projectId: 'market-linkage-application',
    authDomain: 'market-linkage-application.firebaseapp.com',
    storageBucket: 'market-linkage-application.firebasestorage.app',
    measurementId: 'G-2SYRB0V0WE',
  );
}
